# Generated by Django 5.1.6 on 2025-04-24 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Art Categories',
            },
        ),
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('medium', models.CharField(choices=[('oil', 'Oil on Canvas'), ('acrylic', 'Acrylic'), ('watercolor', 'Watercolor'), ('digital', 'Digital Art'), ('photography', 'Photography'), ('mixed', 'Mixed Media'), ('sculpture', 'Sculpture'), ('other', 'Other')], max_length=20)),
                ('width', models.DecimalField(decimal_places=2, help_text='Width in inches/cm', max_digits=6)),
                ('height', models.DecimalField(decimal_places=2, help_text='Height in inches/cm', max_digits=6)),
                ('depth', models.DecimalField(decimal_places=2, default=0, help_text='Depth in inches/cm (if applicable)', max_digits=6)),
                ('year_created', models.IntegerField()),
                ('style', models.CharField(blank=True, max_length=100)),
                ('framing', models.CharField(choices=[('unframed', 'Unframed'), ('framed', 'Framed'), ('gallery_wrapped', 'Gallery Wrapped'), ('matted', 'Matted')], default='unframed', max_length=20)),
                ('status', models.CharField(choices=[('available', 'Available'), ('sold', 'Sold'), ('reserved', 'Reserved'), ('on_display', 'On Display')], default='available', max_length=20)),
                ('is_original', models.BooleanField(default=True)),
                ('has_certificate', models.BooleanField(default=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('featured', models.BooleanField(default=False)),
                ('is_new', models.BooleanField(default=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('views', models.IntegerField(default=0)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artworks', to='accounts.artistprofile')),
                ('categories', models.ManyToManyField(related_name='artworks', to='listings.artcategory')),
            ],
        ),
        migrations.CreateModel(
            name='ArtworkImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='artwork_images/')),
                ('is_primary', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('artwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='listings.artwork')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
